version: "3.9"

services:
  api:
    # container_name: given_name
    build: .
    # ports:
    #   - 3000:3000
  nginx:
    image: nginx:latest
    volumes:
      - ./config:/etc/nginx/config
    depends_on:
      - api
    ports:
      - 3000:3000
